version: "3"
services:
  postgres:
    image: "postgres:14.1"
    container_name: "postgres"
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: "pgc"
      POSTGRES_PASSWORD: "pgc"
      POSTGRES_DB: "pgc"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
      POSTGRES_HOST_AUTH_METHOD: "md5"
